---
# Default labels for CUDN resources
default_subnet_labels:
  osac.io/managed-by: osac-fulfillment

# Default labels for VirtualNetwork resources
default_vn_labels: "{{ {virtual_network_label: virtual_network_name} | default({}) }}"

# Default argument specs (merged with template_parameters)
default_arg_specs: {}

# Layer2 defaults
default_layer2_role: Primary
default_ipam_lifecycle: Persistent
